### ISSUE TITLE
CelesteTAS v3.41.0 / Studio v3.2.0 Roadmap

### ISSUE THREAD

**Issue by psyGamer** [EverestAPI/CelesteTAS-EverestInterop#84]
- [x] Inputs are sent when they shouldn't (need to do remote-debugging with ella since I couldnt reproduce this locally)
- [x] Editor is sometimes only half the expected size
- [x] Resizing sometimes hangs
- [x] Replace old Studio only once download is finished
- [x] Show warning if StudioCom is desynced (cause the download might fail)
- [x] Allow manual downloads by checking the checksum of the Studio .zip (and keep it after installing to avoid reinstalls when just Celeste TAS changed)
- [x] Start and stop folding region if comment isn't empty
- [x] Fix in-Studio total frame count not accounting commands (Should probably pull from the game and then apply diffs instead of trying to calculate it locally? How did Studio v2 do this)
- [x] Turn auto-room-indexing into a tri-state for accounting Read files (maingame requires this)
- [x] Fix UI layout issues with the settings error dialog on WPF
- [x] Fix some UI elements needing a resize before having the correct size
- [x] Incrementally pull command data from CelesteTAS instead of duplicating it inside Studio
- [x] Some file content is missing when using foldings
- [x] Info HUD can fill entire editor (needs scrolling)
- [x] Hide username in title bar
- [x] Dont ask for discarding scratch file if it doesnt contain any non-neutral inputs
- [x] Ignore blank lines when toggling input comments
- [x] Open a text file explaining what happened with Studio v2 on first boot (probably only if `Celeste Studio.toml` exists since that indicates Studio was launched at least once)
- [x] Popout buton is disappearing? (Should probably become a tri-state in the preferences)
- [x] Custom failure message for `Assert` commands
- [x] Update Read/Play commands if auto-indexing changes labels
- [x] Implement "Integrate Read Files"
- [x] #85
